databases:
  - name: Booking
    databaseName: booking_ti4e
    user: booking_ti4e_user

services:
  - type: web
    name: ParkingSlot
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Booking
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false